//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVC_CV.Models.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tbl_Ability
    {
        public int ID { get; set; }
        public string Ability { get; set; }
        public Nullable<int> Proportion { get; set; }
    }
}
